consilium_homepage:
    path:     /
    defaults: { _controller: ConsiliumBundle:Default:index }

consilium_day:
    resource: "@ConsiliumBundle/Resources/config/routing/day.yml"
    prefix:   /day

consilium_activitytype:
    resource: "@ConsiliumBundle/Resources/config/routing/activitytype.yml"
    prefix:   /activitytype

consilium_sportactivity:
    resource: "@ConsiliumBundle/Resources/config/routing/sportactivity.yml"
    prefix:   /sportactivity
