activitytype_index:
    path:     /
    defaults: { _controller: "ConsiliumBundle:ActivityType:index" }
    methods:  GET

activitytype_show:
    path:     /{id}/show
    defaults: { _controller: "ConsiliumBundle:ActivityType:show" }
    methods:  GET

activitytype_new:
    path:     /new
    defaults: { _controller: "ConsiliumBundle:ActivityType:new" }
    methods:  POST

activitytype_edit:
    path:     /{id}/edit
    defaults: { _controller: "ConsiliumBundle:ActivityType:edit" }
    methods:  PUT

activitytype_delete:
    path:     /{id}/delete
    defaults: { _controller: "ConsiliumBundle:ActivityType:delete" }
    methods:  DELETE
